### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/ar.javascript.info#134]
Hi,

Could you please translate phrases in these files?
[copy.zip](https://github.com/javascript-tutorial/ar.javascript.info/files/4997569/copy.zip)

Then zip back and attach here.

Some of them, like ebook-related can be skipped, but they are small, I just gathered all the locales.

**Comment by OmarioHasan** [comment]
Here we are 🚀
With the help of my best friends @Salah856  @mohamedElkast 

[copy.zip](https://github.com/javascript-tutorial/ar.javascript.info/files/5000884/copy.zip)

**Comment by iliakan** [comment]
Nice move:

```
 unrar x copy.zip

...
All ok!
```

You thought I won't guess it's actually rar, didn't ya?

**Comment by OmarioHasan** [comment]
no, I just didn't have a `ZIP` software and make this trick and test it before send it

**Comment by iliakan** [comment]
You can see it here: https://ar.javascript.info/

We're still working on it, adding Arabic to site search.

I'll write when it's ready.

**Comment by OmarioHasan** [comment]
We will proceed to the next topics ASAP 🔥
can't we mention Ng Arab team in about page?

**Comment by iliakan** [comment]
Sure, we should, where was that topic? I remember it was somewhere in the discussion.

Make an issue here please, so that I won't lose it again.

**Comment by OmarioHasan** [comment]
you mean this discussion https://github.com/orgs/javascript-tutorial/teams/translate-ar/discussions/2?from_comment=77

**Comment by iliakan** [comment]
Please translate this, keeping indents. That's for "about" page.

```
title: About the project
text: >
  <p>The Modern JavaScript Tutorial was created in 2007 by Ilya Kantor, and regularly updated since then. New chapters were added, outdated ones - removed, to stay fresh. The PDF version is about 1300 pages, starting from the beginning, and then to advanced topics.</p>
  <p>It's a book, not a video, as for many people reading is faster. Also, books are easier to update, keep modern :).</p>
  <p>The content of this tutorial is <a href="https://github.com/javascript-tutorial/en.javascript.info">open source</a> and everyone is welcome to contribute.</p>

contacts:
  block_title: Contacts
  people:
    ilya_kantor: Ilya Kantor

team:
  block_title: The team
  photo: Photo

  members:
    - name: "Ilya Kantor"
      profileName: 'ilya-kantor'
      url: 'https://javascript.info/profile/ilya-kantor'
      photo: '/team/iliakan.jpg'
      role: creator
    - name: "Alexey Maximov"
      profileName: aleksey-maximov
      url: ''
      photo: '/team/amax.jpg'
      role: admin
    - name: "Artem Beztsinniy"
      profileName: artem-beztsenniy
      url: 'https://javascript.info/profile/artem-beztsenniy'
      photo: '/team/bezart.jpg'
      role: "designer"
    - name: "Sergey Zelenov"
      profileName: sergey-zelenov
      url: 'https://javascript.info/profile/sergey-zelenov'
      photo: '/team/sergey.jpg'
      role: "developer_teacher"
    - name: "Omario Hasan"
      url: 'https://github.com/OmarioHasan'
      photo: '/team/omariohasan.jpg'
      role: "translation_lead"
    - name: "HsoubAcademy"
      url: 'https://github.com/HsoubAcademy'
      photo: '/team/hsoub.jpg'
      role: "translation_lead"
     

  role:
    creator: Author, trainer, JS-developer
    admin: Sysadmin
    teacher: Teacher
    designer: Designer
    markup: Markup
    developer_teacher: JS-developer, teacher
    translation_lead: Translation lead

issues:
  block_title: Bug or typo? Great idea?
  text: Please write at our <a href="https://github.com/javascript-tutorial/en.javascript.info" rel="noopener noreferrer" target="_blank">github</a>.

translation:
  block_title: Help us translate

contributors:
  contributor: Contributor
  contributors: Contributors
  lines: Lines
  percent: Percent
  github_unknown: GitHub account unknown
  show_all: Show all
  description: >
    <p>The list below includes all contributors-authors of 10+ lines of the tutorial. The full list of contributors is available at <a href="#{url}/graphs/contributors">github</a>.</p>
    <p>It's very easy to become listed. Just write an article or propose fixes in the <a href="#{url}">tutorial repository</a>. And get everyone's thanks.</p>
  description_note_en:
    <p>This is the translated version of the <a href="https://javascript.info">tutorial is English</a>.</p>
```
